import json
import os
import sys
import time
from pathlib import Path

# Add project root to sys path
project_root = Path(__file__).resolve().parent.parent.parent
sys.path.append(str(project_root))

from langchain_core.messages import HumanMessage
from langgraph.checkpoint.memory import MemorySaver
from src.agents.graph import build_ask_data_graph
from src.utils.semantic_cache import semantic_cache

def run_evaluation():
    test_file_path = project_root / "tests" / "test_cases.json"
    
    with open(test_file_path, "r", encoding="utf-8") as f:
        data = json.load(f)
        test_cases = data["test_cases"]
        
    print("Starting LLM Agent Evaluation...\n")
    print("Clearing Semantic Cache for baseline measurement...")
    semantic_cache.clear()
    
    graph = build_ask_data_graph(MemorySaver())
    
    results = []
    passed_count = 0
    failed_count = 0
    
    total_latency_cold = 0
    total_latency_hot = 0
    
    print("\n--- Phase 1: Cold Run (Before Cache) ---")
    for tc in test_cases:
        print(f"Evaluating {tc['id']} (Cold)...", end="")
        config = {"configurable": {"thread_id": f"eval_{tc['id']}_cold"}}
        
        start_time = time.time()
        try:
            result_state = graph.invoke(
                {"messages": [HumanMessage(content=tc["query"])]},
                config=config
            )
            latency = time.time() - start_time
            total_latency_cold += latency
            
            # Validation logic
            intent = result_state.get("intent")
            schema = result_state.get("dsl_schema")
            
            passed = True
            errors = []
            
            if "expected_intent" in tc and intent != tc["expected_intent"]:
                passed = False
                errors.append(f"Intent mismatch. Expected '{tc['expected_intent']}', got '{intent}'")
                
            if schema:
                if "expected_metrics" in tc:
                    schema_metrics = getattr(schema, "metrics", []) or []
                    if set(schema_metrics) != set(tc["expected_metrics"]):
                        passed = False
                        errors.append(f"Metrics mismatch. Expected {tc['expected_metrics']}, got {schema_metrics}")
                if "expected_aggregation" in tc:
                    schema_agg = getattr(schema, "aggregation", None)
                    if schema_agg != tc["expected_aggregation"]:
                        passed = False
                        errors.append(f"Aggregation mismatch. Expected '{tc['expected_aggregation']}', got '{schema_agg}'")
                if "expected_chart_type" in tc:
                    schema_chart = getattr(schema, "chart_type", None)
                    if schema_chart != tc["expected_chart_type"]:
                        passed = False
                        errors.append(f"Chart type mismatch. Expected '{tc['expected_chart_type']}', got '{schema_chart}'")
                if "expected_group_by" in tc:
                    schema_group = getattr(schema, "group_by", []) or []
                    if set(schema_group) != set(tc["expected_group_by"]):
                        passed = False
                        errors.append(f"Group By mismatch. Expected {tc['expected_group_by']}, got {schema_group}")
            elif "expected_intent" in tc and tc["expected_metrics"]: 
                passed = False
                errors.append("Schema was not generated by LLM.")
                
            if passed:
                passed_count += 1
                status = "✅ PASSED"
                print(f" -> PASSED ({latency:.2f}s)")
            else:
                failed_count += 1
                status = "❌ FAILED"
                print(f" -> FAILED ({latency:.2f}s)")
                
            tc_result = {
                "id": tc["id"],
                "category": tc["category"],
                "query": tc["query"],
                "status": status,
                "errors": errors,
                "latency_before_cache_sec": latency,
                "audit_trail": schema.model_dump() if schema else None
            }
            results.append(tc_result)
            
        except Exception as e:
            latency = time.time() - start_time
            total_latency_cold += latency
            failed_count += 1
            print(f" -> ERROR ({latency:.2f}s)")
            results.append({
                "id": tc["id"],
                "category": tc["category"],
                "query": tc["query"],
                "status": "❌ ERROR",
                "errors": [str(e)],
                "latency_before_cache_sec": latency,
                "audit_trail": None
            })
            
    print("\n--- Phase 2: Hot Run (After Cache) ---")
    for i, tc in enumerate(test_cases):
        print(f"Evaluating {tc['id']} (Hot)...", end="")
        config = {"configurable": {"thread_id": f"eval_{tc['id']}_hot"}}
        
        start_time = time.time()
        try:
            # We only care about execution time here. Validation is already done in Phase 1.
            graph.invoke(
                {"messages": [HumanMessage(content=tc["query"])]},
                config=config
            )
            latency = time.time() - start_time
            total_latency_hot += latency
            results[i]["latency_after_cache_sec"] = latency
            print(f" -> DONE ({latency:.2f}s)")
        except Exception as e:
            latency = time.time() - start_time
            total_latency_hot += latency
            results[i]["latency_after_cache_sec"] = latency
            print(f" -> ERROR ({latency:.2f}s)")
            
    num_tests = len(test_cases)
    avg_cold = total_latency_cold / num_tests if num_tests > 0 else 0
    avg_hot = total_latency_hot / num_tests if num_tests > 0 else 0
    speedup = ((avg_cold - avg_hot) / avg_cold * 100) if avg_cold > 0 else 0
    
    report_file_path = project_root / "tests" / "evaluation_summary.json"
    
    summary = {
        "title": "Ask Data Agent - Evaluation Summary",
        "total_tests": num_tests,
        "passed": passed_count,
        "failed": failed_count,
        "accuracy_percentage": (passed_count / num_tests) * 100 if num_tests else 0,
        "latency_metrics": {
            "average_latency_before_cache_sec": round(avg_cold, 3),
            "average_latency_after_cache_sec": round(avg_hot, 3),
            "cache_speedup_percentage": round(speedup, 2)
        },
        "detailed_results": results
    }
    
    with open(report_file_path, "w", encoding="utf-8") as f:
        json.dump(summary, f, indent=4, ensure_ascii=False)
            
    print(f"\n================ SUMMARY ================")
    print(f"Accuracy: {(passed_count/num_tests)*100:.2f}%")
    print(f"Avg Latency (Cold): {avg_cold:.3f}s")
    print(f"Avg Latency (Hot) : {avg_hot:.3f}s")
    print(f"Speedup           : {speedup:.2f}%")
    print(f"Report saved to {report_file_path}")
    print("=========================================\n")

if __name__ == "__main__":
    run_evaluation()
