import json
import os
import sys
from pathlib import Path

# Add project root to sys path
project_root = Path(__file__).resolve().parent.parent.parent
sys.path.append(str(project_root))

from langchain_core.messages import HumanMessage
from langgraph.checkpoint.memory import MemorySaver
from src.agents.graph import build_ask_data_graph

def run_evaluation():
    test_file_path = project_root / "tests" / "test_cases.json"
    report_file_path = project_root / "tests" / "evaluation_summary.md"
    
    with open(test_file_path, "r", encoding="utf-8") as f:
        data = json.load(f)
        test_cases = data["test_cases"]
        
    print("Starting LLM Agent Evaluation...\n")
    graph = build_ask_data_graph(MemorySaver())
    
    results = []
    passed_count = 0
    failed_count = 0
    
    for tc in test_cases:
        print(f"Evaluating {tc['id']}...")
        
        # Fresh thread for each test to ensure no memory contamination
        config = {"configurable": {"thread_id": f"eval_{tc['id']}"}}
        
        try:
            result_state = graph.invoke(
                {"messages": [HumanMessage(content=tc["query"])]},
                config=config
            )
            
            intent = result_state.get("intent")
            schema = result_state.get("dsl_schema")
            
            passed = True
            errors = []
            
            # Check Intent
            if "expected_intent" in tc and intent != tc["expected_intent"]:
                passed = False
                errors.append(f"Intent mismatch. Expected '{tc['expected_intent']}', got '{intent}'")
                
            if schema:
                # Check metrics
                if "expected_metrics" in tc:
                    schema_metrics = getattr(schema, "metrics", []) or []
                    if set(schema_metrics) != set(tc["expected_metrics"]):
                        passed = False
                        errors.append(f"Metrics mismatch. Expected {tc['expected_metrics']}, got {schema_metrics}")
                        
                # Check aggregation
                if "expected_aggregation" in tc:
                    schema_agg = getattr(schema, "aggregation", None)
                    if schema_agg != tc["expected_aggregation"]:
                        passed = False
                        errors.append(f"Aggregation mismatch. Expected '{tc['expected_aggregation']}', got '{schema_agg}'")
                        
                # Check chart type
                if "expected_chart_type" in tc:
                    schema_chart = getattr(schema, "chart_type", None)
                    if schema_chart != tc["expected_chart_type"]:
                        passed = False
                        errors.append(f"Chart type mismatch. Expected '{tc['expected_chart_type']}', got '{schema_chart}'")
                        
                # Check group by
                if "expected_group_by" in tc:
                    schema_group = getattr(schema, "group_by", []) or []
                    if set(schema_group) != set(tc["expected_group_by"]):
                        passed = False
                        errors.append(f"Group By mismatch. Expected {tc['expected_group_by']}, got {schema_group}")
                        
            elif "expected_intent" in tc and tc["expected_metrics"]: # If expected metrics is empty, it means we expect NO schema (Out of domain)
                passed = False
                errors.append("Schema was not generated by LLM.")
                
            if passed:
                passed_count += 1
                status = "✅ PASSED"
                print(f"   -> PASSED")
            else:
                failed_count += 1
                status = "❌ FAILED"
                print(f"   -> FAILED")
                
            results.append({
                "id": tc["id"],
                "category": tc["category"],
                "query": tc["query"],
                "status": status,
                "errors": errors,
                "audit_trail": schema.model_dump() if schema else None
            })
            
        except Exception as e:
            failed_count += 1
            print(f"   -> ERROR")
            results.append({
                "id": tc["id"],
                "category": tc["category"],
                "query": tc["query"],
                "status": "❌ ERROR",
                "errors": [str(e)],
                "audit_trail": None
            })
            
    # Write summary report as JSON
    report_file_path = project_root / "tests" / "evaluation_summary.json"
    
    summary = {
        "title": "Ask Data Agent - Evaluation Summary",
        "total_tests": len(test_cases),
        "passed": passed_count,
        "failed": failed_count,
        "accuracy_percentage": (passed_count/len(test_cases))*100 if test_cases else 0,
        "detailed_results": results
    }
    
    with open(report_file_path, "w", encoding="utf-8") as f:
        json.dump(summary, f, indent=4, ensure_ascii=False)
            
    print(f"\nEvaluation complete. Accuracy: {(passed_count/len(test_cases))*100:.2f}%")
    print(f"Report saved to {report_file_path}")

if __name__ == "__main__":
    run_evaluation()
